compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  deepspeed_config_file: configs/ds_lora_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
main_training_function: main
num_machines: 1
num_processes: 8
main_process_ip: 0.0.0.0
main_process_port: 29500
machine_rank: 0
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false